### ISSUE TITLE
.

### ISSUE THREAD

**Issue by graysuit** [mfkl/libvlc-info#1]

**Comment by mfkl** [comment]
You can't easily build libvlc in visual studio. Use clang or gcc, crosscompile from linux.

Check the docker images https://code.videolan.org/videolan/docker-images and see how the CI does it https://code.videolan.org/videolan/vlc/-/blob/master/extras/ci/gitlab-ci.yml

libvlcpp is the C++ wrapper over libvlc.

Don't try to build libvlc if you don't need to, would be my advice.

**Comment by graysuit** [comment]
Thanks sir,
This help will not be forgotten,

I just wanted to know what procedures does libvlc applies,
What things it is using,

> Don't try to build libvlc if you don't need to, would be my advice.

hahhahahha
Yeah, I know as there will be tons of files there,
It will give tons of errors while building.

**Comment by mfkl** [comment]
> I just wanted to know what procedures does libvlc applies,
What things it is using,

I don't know what you mean, sorry.

**Comment by graysuit** [comment]
Sorry,
I mean what codecs, what windows builtin functions, they are using? how they play video ?

I wanted to read the vlc code,
But there are more than 50,000 files,
And code is also very heavy in C which I don't understand,

I wanted to make a very minimal video player 100% in .NET (C#/VB),
Which can support any one codec e.g MP4,

Please give me any advice,
I mostly code in Visual basic and also sometimes C#.

**Comment by mfkl** [comment]
>  I mean what codecs, what windows builtin functions, they are using? how they play video ?

Those questions are very large, you should look into the libvlc docs more in depth.

> I wanted to make a very minimal video player 100% in .NET (C#/VB),

Try the getting started guide of libvlcsharp.

**Comment by graysuit** [comment]
> Those questions are very large, you should look into the libvlc docs more in depth.

Yeah I am and I will keep on searching in depth.

> Try the getting started guide of libvlcsharp.

Before I have been using <a href="https://github.com/ZeBobo5/Vlc.DotNet">Vlc.DotNet</a> for more than 6 months,
And also I made advance sample 1 day ago <a href="https://github.com/graysuit/BasicVLC">BasicVLC</a>,
So that it may be helpful for beginners.

I have asked Jérémy VIGNELLES several questions and also he help me alot,
But he also says that Vlc.DotNet will be archived and libvlcsharp will be maintained,
So sad for Vlc.DotNet (Every Project has an end) :(

libvlcsharp is cross-platform & more easy to use,
So I am also trying to migrate from Vlc.DotNet to libvlcsharp,
**Is there any gitter chat group for libvlcsharp discussion ?**

**I wanted to make a player 100% in .NET,
Because you know every project has an end,
So I can't rely on libvlc if I am a developer.**
THANKS for help sir.

**Comment by mfkl** [comment]
Please read the readme, it contains the answer to your question

**Comment by graysuit** [comment]
Okay I read all,
I have one more question,
How can I remove un needed files and folders from libvlc to lower file size?

I asked this same question to sir Jérémy VIGNELLES,
And he said to test and remove one by one,
I did same thing and removed these folders,
-locale contains languages pack
-win-x64 becoz 32 bit libvlc runs both in 32/64 bits OS.

But also seeing that main folder is of plugins,
If I am not wrong, Not all plugins are used,
So how can I can remove extra files under plugins  folder ?

**Comment by mfkl** [comment]
see https://github.com/mfkl/libvlc-nuget/blob/master/cherry-picking.md

**Comment by graysuit** [comment]
Thanks very much,
I read all cherry picking guide,
**It contains all info about how to exclude or include plugins and dlls,**

**So also is there any other guide to know about which plugin I need or which I don't ?
Mean which plugin is being used** ?
OR
Any wiki where I can know XXXX plugin do XXXX works.

And also tell me sir,
**Does 32 bit libvlc is good for 64 bit OS ?**
What will be consequences if I use 32bit dll on 64bit OS ?
